# **Numpy** 

Esta biblioteca, cuyo nombre significa numerical Python, constituye el núcleo de muchas otras bibliotecas de Python que se han originado a partir de ella. De hecho, NumPy es la biblioteca básica para la computación científica en Python, ya que proporciona estructuras de datos y funciones de alto rendimiento que el paquete básico de Python no proporciona.

NumPy es una biblioteca para el lenguaje de programación Python que da soporte para crear vectores y matrices grandes multidimensionales, junto con una gran colección de funciones matemáticas de alto nivel para operar con ellas.

## Importar la libreria NumPy

In [6]:
import numpy as np 

In [7]:
x = np.array([1,2,3])

In [8]:
np.sin(x)

array([0.84147098, 0.90929743, 0.14112001])

In [9]:
from math import sin

seno = []
for i in [1,2,3]: 
    seno.append(sin(i))
seno


[0.8414709848078965, 0.9092974268256817, 0.1411200080598672]

In [10]:
x = np.array([[1,2,3], [4,5,6]])

In [11]:
y = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])

## **Creación intrinseca de arreglos**

La biblioteca NumPy proporciona un conjunto de funciones que generan ndarrays con contenido inicial, creados con diferentes valores según la función.



In [237]:
np.zeros((3,3))

In [238]:
np.ones((3,3))

In [239]:
np.arange(0,10)

In [240]:
np.arange(4,10)

In [241]:
np.arange(0,12,3)

## **Operaciones básicas**

In [3]:
a = np.arange(0,4)


## **Funciones universales**

In [5]:
a = np.arange(1,6)


In [6]:
np.sqrt(a)

In [7]:
np.log(a)

In [8]:
np.cos(a)

## **Agregar funciones**

In [9]:
a = 5*np.random.random(5)+1

## **Indexando**

In [10]:
a = np.arange(10, 16)

In [12]:
A = np.arange(10,19).reshape((3,3))

In [13]:
A[1,2]

## **Slicing**


In [14]:
a = np.arange(10,16)

In [15]:
a[1:4]

In [16]:
a[1:5:2]

In [17]:
a[::2]

In [47]:
a[:5:2]

array([10, 12, 14])

In [48]:
a[:5:]

array([10, 11, 12, 13, 14])

In [18]:
b = np.arange(10,31)

In [52]:
A = np.arange(10,19).reshape((3,3))

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

## **Condicionales y arreglos Booleanos**

In [19]:
A = np.random.random((4,4))

# **Referencias**

[1]. https://es.wikipedia.org/wiki/NumPy 

[2]. Unpingo J. Python for Probability, Statistics and Machine Learning. Second Edition. Ed. 
Springer.

[3]. Nelli F. Python Data Analytics. With Pandas, NumPy and Matplotlib. Second Ed.